<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE favoritos [
<!ELEMENT favoritos (marcador)>
<!ELEMENT marcador (nombre, uri)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT uri (#PCDATA)>
]>
<marcadores>
    <marcador>
        <nombre>W3C</nombre>
        <uri>http://www.w3.org/</uri>
    </marcador>
    <marcador>
        <nombre>Web Hypertext Application Technology Working Group
        (WHATWG)</nombre>
        <uri>http://www.whatwg.org/</uri>
    </marcador>
</marcadores>