=== antonionavarro04/Lenguaje-de-Marcas/xml/Tema5/dtdDisfraces/disfraces.dtd
<!ELEMENT tienda (disfraces, complementos)>
<!ELEMENT disfraces (disfraz+)>
<!ELEMENT disfraz (nombre, partes?, precio)>
<!ELEMENT partes (parte*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT parte (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT complementos (complemento+)>
<!ELEMENT complemento (nombre, precio, disfrazesCompatibles)>
<!ELEMENT disfrazesCompatibles (disfrazCompatible*)>
<!--El codigo no es requerido-->
<!ATTLIST disfraz codigo CDATA #IMPLIED>
<!ELEMENT disfrazCompatible (#PCDATA)>
<!ATTLIST disfraz sexo (niño|niña|hombre|mujer) #REQUIRED>

=== antonionavarro04/Lenguaje-de-Marcas/xml/Tema5/dtdDisfraces/documento.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "disfraces.dtd">
<tienda>
    <disfraces>
        <disfraz codigo="D1" sexo="hombre">
            <nombre>Torero</nombre>
            <partes>
                <parte>Montera</parte>
                <parte>Chaqueta</parte>
                <parte>Pantalón</parte>
            </partes>
            <precio>45</precio>
        </disfraz>
        <disfraz codigo="D2" sexo="hombre">
            <nombre>Romano</nombre>
            <partes>
                <parte>Pantalon Corto</parte>
            </partes>
            <precio>52</precio>
        </disfraz>
        <disfraz codigo="D3" sexo="niño">
            <nombre>Doctor</nombre>
            <partes>
                <parte>Bata</parte>
            </partes>
            <precio>20</precio>
        </disfraz>
        <disfraz codigo="D4" sexo="mujer">
            <nombre>Doctora</nombre>
            <partes>
                <parte>Bata</parte>
            </partes>
            <precio>30</precio>
        </disfraz>
        <disfraz codigo="D5" sexo="hombre">
            <nombre>Nudista</nombre>
            <precio>10</precio>
        </disfraz>
    </disfraces>
    <complementos>
        <complemento>
            <nombre>Espada</nombre>
            <precio>5</precio>
            <disfrazesCompatibles>
                <disfrazCompatible>Torero</disfrazCompatible>
                <disfrazCompatible>Romano</disfrazCompatible>
            </disfrazesCompatibles>
        </complemento>
        <complemento>
            <nombre>Espada</nombre>
            <precio>5</precio>
            <disfrazesCompatibles>
                <disfrazCompatible>Torero</disfrazCompatible>
            </disfrazesCompatibles>
        </complemento>
    </complementos>
</tienda>
