=== antonionavarro04/Lenguaje-de-Marcas/xml/Tema5/dtdEjemplo/vehiculo.dtd
<!ELEMENT vehiculos (vehiculo*)>
<!ELEMENT vehiculo (fecha, matricula, pago)>
<!ELEMENT pago (inicioPago, finalPago, sancion?)>
<!ELEMENT sancion (horaSancion, foto+)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT inicioPago (#PCDATA)>
<!ELEMENT finalPago (#PCDATA)>
<!ELEMENT horaSancion (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST sancion importe CDATA "35">

=== antonionavarro04/Lenguaje-de-Marcas/xml/Tema5/dtdEjemplo/documento.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehiculos SYSTEM "vehiculo.dtd">
<vehiculos>
    <vehiculo>
        <fecha></fecha>
        <matricula></matricula>
        <pago>
            <inicioPago></inicioPago>
            <finalPago></finalPago>
            <sancion importe="5">
                <horaSancion></horaSancion>
                <foto></foto>
            </sancion>
        </pago>
    </vehiculo>
</vehiculos>
