=== antonionavarro04/Lenguaje-de-Marcas/xml/Tema5/dtdCompañeros/dtdSoldados/soldados.dtd
<!ELEMENT soldados (soldado+)>
<!ELEMENT soldado (nombre, fechaServicio, habilidadesEspeciales?, anotaciones?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaServicio (#PCDATA)>
<!ELEMENT habilidadesEspeciales (habilidad*)>
<!ELEMENT habilidad (#PCDATA)>
<!ELEMENT anotaciones (anotacion*)>
<!ELEMENT anotacion (#PCDATA)>
<!ATTLIST soldado id ID #IMPLIED>
<!ATTLIST soldado estado CDATA #REQUIRED>
<!ATTLIST soldado unidad CDATA #REQUIRED>
<!ATTLIST soldado nivel CDATA #REQUIRED>
<!ATTLIST habilidad nombre CDATA #REQUIRED>
<!ATTLIST habilidad profilencia CDATA #REQUIRED>

=== antonionavarro04/Lenguaje-de-Marcas/xml/Tema5/dtdCompañeros/dtdSoldados/documento.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE soldados SYSTEM "soldados.dtd">
<soldados>
    <soldado id="S1" estado="activo" unidad="1" nivel="1">
        <nombre>John</nombre>
        <fechaServicio>2010-01-01</fechaServicio>
        <habilidadesEspeciales>
            <habilidad nombre="sigilo" profilencia="alta"/>
        </habilidadesEspeciales>
        <anotaciones>
            
        </anotaciones>
    </soldado>
    <soldado id="S303" estado="activo" unidad="4A" nivel="3">
        <nombre>David</nombre>
        <fechaServicio></fechaServicio>
        <habilidadesEspeciales>
            <habilidad nombre="sigilo" profilencia="alta"/>
            <habilidad nombre="disparo" profilencia="alta"/>
        </habilidadesEspeciales>
        <anotaciones>
            <anotacion>El soldado David es un excelente tirador</anotacion>
        </anotaciones>
    </soldado>
</soldados>
